accent = "#ff72b6"
cursor = "#fff5fb"
foreground = "#ffeaf5"
background = "#190f35"
selection_foreground = "#190f35"
selection_background = "#70f5d2"
color0 = "#26134b"
color1 = "#ff4f9b"
color2 = "#48e4bf"
color3 = "#ffd35c"
color4 = "#8da8ff"
color5 = "#d58bff"
color6 = "#70f5d2"
color7 = "#f8d9ed"
color8 = "#684276"
color9 = "#ff8ac5"
color10 = "#8bffe0"
color11 = "#ffe594"
color12 = "#b2c2ff"
color13 = "#edb8ff"
color14 = "#a8ffe7"
color15 = "#fff7fc"
