background = #190f35
foreground = #ffeaf5
cursor-color = #fff5fb
selection-background = #70f5d2
selection-foreground = #190f35
palette = 0=#26134b
palette = 1=#ff4f9b
palette = 2=#48e4bf
palette = 3=#ffd35c
palette = 4=#8da8ff
palette = 5=#d58bff
palette = 6=#70f5d2
palette = 7=#f8d9ed
palette = 8=#684276
palette = 9=#ff8ac5
palette = 10=#8bffe0
palette = 11=#ffe594
palette = 12=#b2c2ff
palette = 13=#edb8ff
palette = 14=#a8ffe7
palette = 15=#fff7fc
background-opacity = 0.86
